import = [
  #"~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

live_config_reload = true

#[[keyboard_bindings]]
#key = "Space"
#mods = "Control"
#mode = "~Search"
#action = "ToggleViMode"
#
#[[keyboard_bindings]]
#key = "Key6"
#mods = "Control"
#chars = "\u001e"
#
#[[keyboard_bindings]]
#key = "Key9"
#mods = "Command"
#action = "ResetFontSize"


[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[window]
#padding.x = 10
#padding.y = 10
#decorations = "none"
dynamic_padding = true
option_as_alt = "Both"
decorations = "Buttonless"

opacity = 0.7
blur = true


[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 16

[scrolling]
history = 10_000

[cursor]
blink_interval = 600

  [cursor.style]
  shape = "Block"
  blinking = "Always"



